name: elopage_performance
description: A new Flutter project.
publish_to: "none"
version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  atlassian_apis: ^0.8.0
  cupertino_icons: ^1.0.2
  flutter:
    sdk: flutter
  get_it: ^7.2.0
  google_fonts: ^3.0.1
  result:
    path: ../../../work/elopage_mobile/packages/independent/result

dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
